### ISSUE TITLE
Math bug using array size as operands

### ISSUE THREAD

**Issue by AlexisTM** [gaborsch/rocky#37]
## Description

When using the size of the array as an operand, the output will be incorrect.

## Minimum viable bug

```
Total is 0
Rock the result with 1000
Rock the result with 2000
Say the result
Say Total
Let Total be with the result
Say Total
```

## Expected output
(from https://codewithrockstar.com/online)

```
2
0
2
```

## Actual output
(from rocky)

```
2
0
3
```

**Comment by hugobuddel** [comment]
Oh I should have payed more attention because I just posted a similar bug as #39 . Just commenting here to link the issues.

What rocky seems to do when adding an integer and and array is always add 1 and the length of the array, irrespective of the value of the integer. So even if you'd start with a Total of 6, you'd still end up with a Total of 3. Subtracting from an array is even more interesting, see https://github.com/gaborsch/rocky/issues/39#issuecomment-995653558

**Comment by AlexisTM** [comment]
How come we bumped into it at the same time? Are you also doing the Advent of Code in Rockstar?

Also, I do have that in a loop but the final result is only `+1`.

```
Total is 0
Rock the result with 1000
Rock the result with 2000
Say the result
Say Total
Let Total be with the result
Let Total be with the result
Let Total be with the result
Say Total
```

Will result in:

```
2
0
7 (This should be 6)
```

**Comment by gaborsch** [comment]
This mystical +1 in array size is because addition operation behaves differently in Rocky and Satriani,

In Rocky, adding to an array means extending it with that value (that means, adding 1 more element), resulting a new array. In the example above (`Let Total be with the result`), `Total` is an array. Then, `Say Total` evaluates it in scalar context, thus returning the length of the extended array, which is 1 more than the length of the original array.

Satriani, on the other hand, evaluates the array as a scalar during the addition (taking the original length), and adding it to `Total` (which is 0), so the result is a scalar value (of numeric type).

**Comment by AlexisTM** [comment]
This behavior makes it kind of impossible to work with the array size :(

**Comment by gaborsch** [comment]
Yes, the addition operation needs to be changed, and that will resolve the incompatibility issue, 

Also, we could raise the question in Rockstar, maybe the array handling could be redefined in the language spec.

**Comment by hugobuddel** [comment]
You can get the array size by multiplying with 1. E.g. I like this construct with `of`

```
The century is frightening
The king was "whatever"
Cut the king
Let Heman be the king of the century
Shout Heman
```

 I thought it would be a nice change to use plus 0 instead, using `with`, something like:
```
Shared was nothing
The drugs were "whatever"
Cut the drugs into the bags
Let the drugs be shared with the bags
Shout the drugs
```

Both these result in 8 in satriani, but in rocky the second is 9 (or well, `the drugs` is an array of size 9).

And indeed I got here through the advent of code. Haven't had so much fun programming in a while. And these little investigations perhaps even add to the fun.

**Comment by AlexisTM** [comment]
Day 1 and 2 were obvious, then I skipped to day 6 and trying to make it more efficient for the step 2, but the array handling is preventing it to work. I will switch to Satriani for the time being. (and add the tests)

**Comment by gaborsch** [comment]
Changed the add/subtract ways to be compatible with Satriani in compatibility mode. Extension mode still behaves the same as before.

**Comment by AlexisTM** [comment]
Thanks!

**Comment by gaborsch** [comment]
Actually I introduced a bug with some of the late changes, which were fixed in https://github.com/gaborsch/rocky/commit/1f857296b0a71667d5818dcb41e01e1d8469fa07 - please update!

**Comment by AlexisTM** [comment]
Updating now, thanks for your meme work, it is magnificent! ;)
