### ISSUE TITLE
Slice operator seems broken

### ISSUE THREAD

**Issue by duckyluuk** [gaborsch/rocky#58]
In the [keyword list](https://github.com/gaborsch/rocky/blob/master/src/rockstar/parser/Keyword.java) I found the TILL and FROM operators which are supposed to be used for [array slicing](https://github.com/gaborsch/rocky/blob/master/src/rockstar/expression/SliceExpression.java). These keywords seem to be an undocumented part of the Rocky specific extensions, but there is still a test for them in [programs/array_tests/list_functions.rock](https://github.com/gaborsch/rocky/blob/master/programs/array_tests/list_functions.rock). However, the test doesn't work at all and gives a bunch of errors.

I thought these functions would be quite useful so made my own quick test program to see if they work:

```
cut "ABCDEFGHIJ" into letters
sliced = letters till 3
join sliced
say sliced

sliced = letters from 3
join sliced
say sliced
```

the first part with the `sliced = letters till 3` works properly and the result prints out `ABCD` as expected. However, the `sliced = letters from 3` gives the following error: 
`Error: Non-Object referenced: 3 is NUMBER`

`sliced = letters from 3 till 3` gives the same error as well.

It seems that this is due to the collision of `from` also being an alias for the `on` keyword.

**Comment by gaborsch** [comment]
Yes, that was part of the Rocky arrays extensions, but abandoned when Rockstar language added array handling. All currently supported features can be found here: https://github.com/gaborsch/rocky/tree/master/programs/tests/fixtures/Rocky_ext/array_ext
The `programs/array_tests` folder has all the abandoned features, that's why it throws errors. 

But you are right, this feature may worth to resurrect, however the collision with `on` causes issues, I will implement it with `since` and `till` keywords, because they are not conflicting.

**Comment by gaborsch** [comment]
I also included your example as a test.
